spring:
  profiles:
    active: docker
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: produto
          uri: lb://PRODUTO-SERVICE
          predicates:
            - Path=/produto/**
          filters:
            - StripPrefix=1
        - id: pedido
          uri: lb://PEDIDO-SERVICE
          predicates:
            - Path=/pedido/**
          filters:
            - StripPrefix=1
        - id: vendedor
          uri: lb://VENDEDOR-SERVICE
          predicates:
            - Path=/vendedor/**
          filters:
            - StripPrefix=1
        - id: autenticator
          uri: lb://AUTENTICATOR-SERVICE
          predicates:
            - Path=/autenticator/**
          filters:
            - StripPrefix=1
        - id: nota-fiscal
          uri: lb://NOTA-FISCAL-SERVICE
          predicates:
            - Path=/nota-fiscal/**
          filters:
            - StripPrefix=1
        - id: avaliacao
          uri: lb://AVALIACAO-SERVICE
          predicates:
            - Path=/avaliacao/**
          filters:
            - StripPrefix=1
        - id: imposto-service
          uri: lb://IMPOSTO-SERVICE
          predicates:
            - Path=/imposto-service/**
          filters:
            - StripPrefix=1
server:
  port: 9999

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka