spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: produto
          uri: lb://PRODUTO-SERVICE
          predicates:
            - Path=/produto/**
          filters:
            - StripPrefix=1
            - name: Retry
              args:
                retries: 3
                methods: GET,POST
                backoff:
                  initialInterval: 500ms
                  maxInterval: 2s
                  multiplier: 1.5
        - id: pedido
          uri: lb://PEDIDO-SERVICE
          predicates:
            - Path=/pedido/**
          filters:
            - StripPrefix=1
        - id: avaliacao
          uri: lb://AVALIACAO-SERVICE
          predicates:
            - Path=/avaliacao/**
          filters:
            - StripPrefix=1
server:
  port: 9999

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka